local inventory = require("ContainerComponent.inventory")
local localNet = require("localNet")
local peripheral = require("peripheral")
local containerMaker = require("containerMaker")

local function makeStone(count)
    return inventory.FakeItem.make("minecraft:stone", count or 1, 64, {})
end

local function makeSimpleSword(count)
    return inventory.FakeItem.make("a546:simple_sword", count or 1, 1, { damage = 0 })
end

describe("物品容器组件（inventory）模块测试", function()
    it("FakeItem创建函数测试", function()
        local grass = inventory.FakeItem.make("minecraft:grass", 22, 64, {})
        assert.Equal(grass.name, "minecraft:grass")
        assert.Equal(grass.count, 22)
        assert.Equal(grass.stackLimit, 64)
        assert.Same(grass.nbt, {})
    end)
    it("组件应该将自身注入dev接口", function()
        local testInventory = inventory.make(28, 1)
        assert.same(testInventory, testInventory.dev.inv)
    end)

    --#region addItem
    it("测试组件内容操作接口添加物品的能力", function()
        local testInventory = inventory.make(28, 1)
        local stone = makeStone(28)
        for i = 1, testInventory.invSize, 1 do
            local actuallyTransfer = testInventory.dev:addItem(stone, i)
            assert.is.equal(actuallyTransfer, 28)
            assert.are.same(testInventory.itemList[i], stone)
        end
    end)
    it("向特定槽位添加不超过单槽位堆叠上限的物品", function()
        local testInventory = inventory.make(28, 1)
        local stone = makeStone(28)
        for i = 1, testInventory.invSize, 1 do
            local actuallyTransfer = testInventory.dev:addItem(stone, i)
            assert.is.equal(actuallyTransfer, 28)
            assert.are.same(testInventory.itemList[i], stone)
        end
    end)
    it("向特定槽位添加超过单槽位堆叠上限的物品", function()
        local testInventory = inventory.make(28, 0.5)
        local stone = makeStone(64)
        for i = 1, testInventory.invSize, 1 do
            local actuallyTransfer = testInventory.dev:addItem(stone, i)
            assert.is.equal(actuallyTransfer, 32)
        end
    end)
    it("向不存在的槽位添加物品应该报错", function()
        local size = 28
        local coefficient = 1
        local testInventory = inventory.make(size, coefficient)
        local stone = makeStone(1)
        assert.are.error(function()
            testInventory.dev:addItem(stone, -1)
        end)
        assert.are.error(function()
            testInventory.dev:addItem(stone, size + 1)
        end)
    end)
    it("添加超过单槽位容量上限的物品应该将更多物品转移到其他槽位", function()
        local testInventory = inventory.make(28, 1 / 64)
        local stone = makeStone(64)
        testInventory.dev:addItem(stone)
        for i = 1, 28, 1 do
            assert.is.equal(1, testInventory.itemList[i].count)
        end
    end)
    --#endregion

    --#region removeItem
    it("移除整个槽位的物品", function()
        local testInventory = inventory.make(28, 1)
        local stone = makeStone(63)
        testInventory.dev:addItem(stone, 1)
        local actuallyTransfer = testInventory.dev:removeItem(1)
        assert.is.same(actuallyTransfer, stone)
        assert.is.equal(testInventory.itemList[1], nil)
    end)
    it("从不存在的槽位移除物品应该报错", function()
        local testInventory = inventory.make(28, 1)
        assert.is.error(function()
            testInventory.dev:removeItem(-1)
        end)
        assert.is.error(function()
            testInventory.dev:removeItem(testInventory.invSize + 1)
        end)
    end)
    it("移除过量的物品", function()
        local testInventory = inventory.make(28, 1)
        local stone = makeStone(63)
        testInventory.dev:addItem(stone, 1)
        local actuallyTransfer = testInventory.dev:removeItem(1, 630)
        assert.is.same(actuallyTransfer, stone)
        assert.is.equal(testInventory.itemList[1], nil)
    end)
    it("移除部分物品", function()
        local testInventory = inventory.make(28, 1)
        local stone = makeStone(63)
        testInventory.dev:addItem(stone, 1)
        local actuallyTransfer = testInventory.dev:removeItem(1, 62)
        stone.count = 62
        assert.is.same(actuallyTransfer, stone)
        stone.count = 1
        assert.is.same(testInventory.itemList[1], stone)
    end)
    --#endregion
end)

describe("对于pullItems和pushItems函数", function()
    local chestA
    local chestB
    local aNet
    local bNet
    describe("在不同网络中", function()
        before_each(function()
            aNet = localNet.make()
            bNet = localNet.make()
            chestA = containerMaker.make("chest", inventory.make(28, 1))
            chestB = containerMaker.make("chest", inventory.make(28, 1))
            localNet.addPeripheral(aNet, chestA)
            localNet.addPeripheral(bNet, chestB)
        end)
        after_each(function()
            localNet.removePeripheral(aNet, chestA.name)
            localNet.removePeripheral(bNet, chestB.name)
        end)
        it("容器间转移物品应该报错", function()
            local a = peripheral.warp(chestA.name)
            assert.has.error(function()
                a.pushItems(chestB.name, 1)
            end)
        end)
    end)
    describe("在同一个网络中", function()
        before_each(function()
            aNet = localNet.make()
        end)
        describe("两个容器具有不同的堆叠系数", function()
            before_each(function()
                local aInventory = inventory.make(28, 4)
                chestA = containerMaker.make("chest", aInventory)
                chestB = containerMaker.make("chest", inventory.make(28, 0.5))
                aInventory.dev:addItem(inventory.FakeItem.make("minecraft:glass", 33, 64, {}), 1)
                localNet.addPeripheral(aNet, chestA)
                localNet.addPeripheral(aNet, chestB)
            end)
            after_each(function()
                localNet.removePeripheral(aNet, chestA.name)
                localNet.removePeripheral(aNet, chestB.name)
            end)
            it("两者间可以互相推送物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(a.pushItems(chestB.name, 1), 33)
                assert.is.equal(b.pushItems(chestA.name, 1), 32)
                assert.is.equal(b.pushItems(chestA.name, 2), 1)
            end)
            it("两者间可以互相拉取物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1), 33)
                assert.is.equal(a.pullItems(chestB.name, 1), 32)
                assert.is.equal(a.pullItems(chestB.name, 2), 1)
            end)
            it("可以使用limit参数指定最多转移多少物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1, 5), 5)
                assert.is.equal(a.pullItems(chestB.name, 1), 5)
            end)
            it("可以使用toSlot参数指定目标槽位", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1, 5, 8), 5)
                assert.is.equal(a.pullItems(chestB.name, 1), 0)
                assert.is.equal(a.pullItems(chestB.name, 8), 5)
            end)
        end
        )
        describe("两个容器具有相同的堆叠系数", function()
            before_each(function()
                local aInventory = inventory.make(28, 1)
                chestA = containerMaker.make("chest", aInventory)
                chestB = containerMaker.make("chest", inventory.make(28, 1))
                aInventory.dev:addItem(inventory.FakeItem.make("minecraft:glass", 10, 64, {}), 1)
                localNet.addPeripheral(aNet, chestA)
                localNet.addPeripheral(aNet, chestB)
            end)
            after_each(function()
                localNet.removePeripheral(aNet, chestA.name)
                localNet.removePeripheral(aNet, chestB.name)
            end)
            it("超出槽位限制时会报错", function()
                local a = peripheral.warp(chestA.name)
                assert.has.error(function()
                    a.pushItems(chestB.name, 99)
                end)
                assert.has.error(function()
                    a.pushItems(chestB.name, -99)
                end)
            end)
            it("两者间可以互相推送物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(a.pushItems(chestB.name, 1), 10)
                assert.is.equal(b.pushItems(chestA.name, 1), 10)
            end)
            it("两者间可以互相拉取物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1), 10)
                assert.is.equal(a.pullItems(chestB.name, 1), 10)
            end)
            it("可以使用limit参数指定最多转移多少物品", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1, 5), 5)
                assert.is.equal(a.pullItems(chestB.name, 1), 5)
            end)
            it("可以使用toSlot参数指定目标槽位", function()
                local a = peripheral.warp(chestA.name)
                local b = peripheral.warp(chestB.name)
                assert.is.equal(b.pullItems(chestA.name, 1, 5, 8), 5)
                assert.is.equal(a.pullItems(chestB.name, 1), 0)
                assert.is.equal(a.pullItems(chestB.name, 8), 5)
            end)
        end)
    end)
end)

describe("对于list函数", function()
    local aNet = localNet.make()
    local inventoryA = inventory.make(28, 1)
    local chestA = containerMaker.make("chest", inventoryA)
    inventoryA.dev:addItem(inventory.FakeItem.make("minecraft:glass", 15, 64, {}), 3)
    inventoryA.dev:addItem(inventory.FakeItem.make("minecraft:stone", 17, 64, {}), 4)
    inventoryA.dev:addItem(inventory.FakeItem.make("turtle:test_item", 89, 128, { active = true }), 5)
    inventoryA.dev:addItem(inventory.FakeItem.make("turtle:test_item", 89, 128, { active = false }), 6)
    localNet.addPeripheral(aNet, chestA)
    it("可以正确返回容器内的物品信息", function()
        local a = peripheral.warp(chestA.name)
        local itemList = a.list()
        assert.is.Table(itemList)
        assert.is.equal(itemList[3].name, "minecraft:glass")
        assert.is.equal(itemList[3].count, 15)
        assert.is.equal(itemList[4].name, "minecraft:stone")
        assert.is.equal(itemList[4].count, 17)
        assert.is.equal(itemList[5].name, "turtle:test_item")
        assert.is.equal(itemList[5].count, 89)
        assert.is.equal(itemList[6].name, "turtle:test_item")
        assert.is.equal(itemList[6].count, 89)
        assert.is.Not.Same(itemList[5].nbt, itemList[6].nbt)
    end)
end)

describe("对于getItemDetail函数", function()
    pending("应该返回目标槽位物品的详细信息", function()

    end)
    pending("输入不存在的槽位时应该报错", function()

    end)
    pending("目标槽位不存在时应该返回nil", function()

    end)
end)

describe("对于size函数", function()
    pending("应该返回容器的槽位总数", function()

    end)
end)

describe("对于getItemLimit函数", function()
    pending("应该返回CC文档中描述的值", function()
        --由于CC文档中不怎么清楚的描述和游戏内诡异的行为，我只能这么写
    end)
end)
